/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MIdRouteImport } from './routes/m/$id'
import { Route as IDataRouteImport } from './routes/i/$data'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MIdRoute = MIdRouteImport.update({
  id: '/m/$id',
  path: '/m/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IDataRoute = IDataRouteImport.update({
  id: '/i/$data',
  path: '/i/$data',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/i/$data': typeof IDataRoute
  '/m/$id': typeof MIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/i/$data': typeof IDataRoute
  '/m/$id': typeof MIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/i/$data': typeof IDataRoute
  '/m/$id': typeof MIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/i/$data' | '/m/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/i/$data' | '/m/$id'
  id: '__root__' | '/' | '/i/$data' | '/m/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IDataRoute: typeof IDataRoute
  MIdRoute: typeof MIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$id': {
      id: '/m/$id'
      path: '/m/$id'
      fullPath: '/m/$id'
      preLoaderRoute: typeof MIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$data': {
      id: '/i/$data'
      path: '/i/$data'
      fullPath: '/i/$data'
      preLoaderRoute: typeof IDataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IDataRoute: IDataRoute,
  MIdRoute: MIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
